### ISSUE TITLE
"supported systems" is wrongly displayed

### ISSUE THREAD

**Issue by qji77** [SteamDatabase/SteamDatabase#435]
The Grid Autosport (App ID 255220) is supported on all the 3 platforms (Windows/OS X/Linux), it's visible on the store page, but on SteamDB site the "supported systems" shows only Windows.
Compare these 2 pages:
https://steamdb.info/app/255220/config/
http://store.steampowered.com/app/255220/

**Comment by Marlamin** [comment]
Tell the devs to update their information in Steamworks, we get this from Steam:
`"oslist"		"windows"`
So not exactly in our control. Sorry!

**Comment by qji77** [comment]
Interesting. Then how a Steam client can decide what to display? :)

**Comment by Marlamin** [comment]
Probably through a plethora of hackfixes that we're not going to implement on SteamDB.

**Comment by qji77** [comment]
I have no clue how this "dump" what you get from steam looks like... but checking the history of this app in the changes I see:
launch/0/config/oslist: windows
launch/1/config/oslist: windows
launch/2/config/oslist: linux
launch/3/config/oslist: macos
So looks like they have multiple "oslist".

**Comment by Marlamin** [comment]
We use the oslist from the common set of keys because it is generally the most correct indication, not config which can also have oslists for things that aren't yet available to the public. See dump [here](https://xen.steamdb.info/app/255220.vdf). It is up to developers to keep information in the Steam backend up to date.
